### PR TITLE
feat: add custom command palette for extension commands (#17)

### PR DESCRIPTION
**Pull request by ASANIYAN**
- Implemented a custom command palette accessible via keyboard shortcuts (e.g., Ctrl+Shift+1) to execute extension commands like save, append, and clear data.
- Integrated commands with Mac (MacCtrl) and Windows (Ctrl) keyboard shortcuts.
- Updated manifest.json to define shortcut commands and ensure cross-platform compatibility.
- Improved usability and accessibility by allowing users to trigger key extension functionalities quickly.

### CODE REVIEW

**Comment by ASANIYAN** [comment]
@atj393

**Comment by atj393** [comment]
@ASANIYAN What is the issue number?

**Comment by ASANIYAN** [comment]
Issue #17

**Comment by ASANIYAN** [comment]
@atj393

**Comment by ASANIYAN** [comment]
@atj393 Is there anything you need me to make corrections to?

I noticed my PR has not been merged yet

**Comment by atj393** [comment]
@ASANIYAN I could not review it in the last two days. I will do it now and let you know.

**Review by atj393 — DISMISSED** [review]

**Comment by atj393** [comment]
@ASANIYAN Great Work! Thanks for your contribution.

**Comment by ASANIYAN** [comment]
@atj393 You closed my PR and did not merge.

Is there any correction you want me to make?

**Comment by atj393** [comment]
@ASANIYAN It should been merged automatically, but I think because of this conflicts
image
Can you resolve this and let me know? Thanks.

**Comment by ASANIYAN** [comment]
I don't have the required access to resolve the conflicts.

The conflict occurs because of the new commands object I added in the manifest.json file, aside from that, everything seems to be fine.

@atj393

**Comment by atj393** [comment]
image
@ASANIYAN do you also see this in your repository? Then click the "Sync" button and it will sync your forked copy with the latest.

**Comment by ASANIYAN** [comment]
I just fixed it @atj393 

Thank you for pointing that out.

**Review by atj393 — APPROVED** [review]

**Comment by atj393** [comment]
@ASANIYAN merged. Thanks!

**Pull request merged**
